### PR TITLE
Polish Translation

### PR DESCRIPTION
**Pull request by revsx**
Polish translation with 592 new words added.

### CODE REVIEW

**Comment by Jqstln** [comment]
Please keep the `template.md` as the same file name, and create a new JSON file with the language name and put the JSON in there. After that we can merge the pull request 👍🏼

Like this file: https://github.com/ARC8-Official/ARC8-Translations/blob/master/languages/english.json

**Comment by revsx** [comment]
done, do I have to make a new pull request?

**Comment by Justinnnp** [comment]
> done, do I have to make a new pull request?

No, just update this one.

**Comment by revsx** [comment]
yup, I did.

**Review by Jqstln — COMMENTED** [review]
Thank you for this, I'll wait for the other team to review this and then we will merge.

**Review by Justinnnp — COMMENTED** [review]
Looks good, thanks for all the effort! 🙂

**Pull request merged**
